name: Continuous integration Workflow

on:
  push:
    branches:
      - main

jobs:
  run_test:
    name: 'Run unit tests'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]
    steps:
      - uses: actions/checkout@v4
        name: 'Checkout Repository'
      - name: 'Install Dependencies'
        run: npm install
      - name: 'Run Tests'
        run: npm run test